services:
    biig_domain.dispatcher:
        class: Biig\Component\Domain\Event\DomainEventDispatcher

    Biig\Component\Domain\Event\DomainEventDispatcher: '@biig_domain.dispatcher'
    Biig\Component\Domain\Event\DomainEventDispatcherInterface: '@Biig\Component\Domain\Event\DomainEventDispatcher'

    Biig\Component\Domain\Model\Instantiator\Instantiator:
        arguments:
            - "@biig_domain.dispatcher"

    biig_domain.instantiator.default:
        alias: Biig\Component\Domain\Model\Instantiator\Instantiator
        public: true

